name: Deploy React Vite to GoDaddy

on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build
        env:
          VITE_API_URL: https://trymakhana-website-backend.onrender.com
          VITE_FIREBASE_API_KEY: AIzaSyD3hp5QEv4kWv3mksvKJsUgF7H6RwGKR7U
          VITE_FIREBASE_AUTH_DOMAIN: makhana-magic-e6ffe.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: makhana-magic-e6ffe
          VITE_FIREBASE_STORAGE_BUCKET: makhana-magic-e6ffe.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: 64623810448
          VITE_FIREBASE_APP_ID: 1:64623810448:web:85b351dd6d2c1362ffc515

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: medimapdiagnostics.com
          username: development@trymaakhanastores.com
          password: development123
          protocol: ftps
          local-dir: ./dist/
          server-dir: ./public_html/trymaakhanastores.com
